name: Publish to Github Pages
on:
  push:
    branches:
      - main
      - 7-github-pagesを有効化する
env:
  DOMAIN: story.kasai-san.dev
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.0'
          extended: true
      - name: Build
        run: hugo --minify --baseURL https://${{ env.DOMAIN }}/
        env:
          HUGO_ENV: production
      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: ${{ env.DOMAIN }}
          publish_dir: ./public
