name: build-devcontainer
on:
  push:
    branches:
      - main
      - test/**
    paths:
      - .github/workflows/build-devcontainer.yaml
      - .devcontainer/Dockerfile
env:
  REGISTRY: ghcr.io
  BRANCH_TAG: latest
jobs:
  build_devcontainer:
    name: Build devontainer's image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to the Container Registry (Github Packages)
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set environment variables for metadata
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: echo 'BRANCH_TAG=main' >> $GITHUB_ENV
    - name: Set metadata for Docker Image
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}
        flavor: |
          latest=true
          prefix=devcontainer-,onlatest=true
        tags: |
          type=sha,format=long
          type=raw,value=${{ env.BRANCH_TAG }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        file: .devcontainer/Dockerfile
        platforms: linux/amd64
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
          